### ISSUE TITLE
Use loopback enode URLs

### ISSUE THREAD

**Issue by DemiMarie** [poanetwork/pos-test-setup#6]
On systems with firewalls enabled, the current setup can fail for no apparent reason, because Parity produces enodes that use the IP address of the machine we are running on.  Fortunately, we can use the Node.js `url` module to replace this IP address with `127.0.0.1`, which should not be blocked by firewalls.

The failure usually shows up as the number of peers decreasing for no apparent reason.  This took me almost a whole day to debug.

**Comment by vkomenda** [comment]
Fixed by #7.
